### ISSUE TITLE
Request: LICENSE

### ISSUE THREAD

**Issue by monrax** [liamg/magic#8]
Hello!

I've been playing with this repo for a couple weeks now, and I'd like to include it in a middleware-like tool called [`logger-go`](https://github.com/resurfaceio/logger-go) that logs HTTP requests an responses and sends them to a DB. The plan is to attempt to read body bytes from HTTP responses based on both the `Content-Encoding` header and the magic bytes found in the payload. However, I just noticed the repo doesn't have a license.

Do you have any plans to add an open source license to this repo in the foreseeable future @liamg ?

**Comment by liamg** [comment]
Hey, sure, I just added the unlicense 👍
